export const EVENT_TAGS_WITH_IMAGES = new Set([
  "AAPI",
  "Art & Culture",
  "BLM",
  "Climate Change",
  "Democratic Party",
  "Disability Rights",
  "Earth Day",
  "Education",
  "Environmental Protection",
  "Family Friendly",
  "Healthcare",
  "Housing Rights",
  "Immigration",
  "International Affairs",
  "Labor Rights",
  "LGBTQ+",
  "Local Politics",
  "Mutual Aid",
  "National Politics",
  "Parks",
  "State Politics",
  "Ukraine",
  "Volunteering",
  "Voting Rights",
  "Women's Rights",
  "Abortion Rights"
]);
